language: node_js
node_js:
  - node
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: build
  skip_cleanup: true
  keep_history: true
  project_name: pgp2go
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: always
