name: CI

on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 1 * *'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - name: Upload to GitHub Pages
        if: matrix.node-version == '12.x' && (github.event_name == 'schedule' || github.event_name == 'release')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true
